version: '3'

services:
  backend:
      build:
        context: ./backend
      ports:
        - "3001:3001"
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      depends_on:
        - database

  frontend:
      build:
        context: ./frontend
      ports:
        - "3000:3000"
      depends_on:
        - backend

  database:
      image: postgres:latest
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"